config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :items
  end

  resources :items, only: [:show, :update]

  root 'lists#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :List
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @list =List.find(params[:list_id])
  end

  def create
    @item = Item.new(item_params)
    @item.completed = false
    if @item.save
      redirect_to "/lists/#{params[:list_id]}"
    else
      render :new
    end

  end


  # t.datetime "due_date"
  # t.boolean  "completed"

  def show
    @item = Item.find(params[:id])
    render json: @item
  end

  def edit
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    @list = List.find(@item.list_id)
    # redirect_to list_path(@list)
    # redirect_to :controller => "lists", :action => "show", :id => @list.id
    respond_to do |format|
      format.html { redirect_to(list_path(@list)) }
      format.json { render json: @list } #this is the response for the AJAX call.
    end


  end

  def destroy
    item = Item.find(params[:id])
    list = List.find(item.list_id)
    item.destroy
    redirect_to list
  end

  private
  def item_params
    return params[:item].permit(:description, :list_id, :completed)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to '/'
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @list }
    # end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update!(list_params)
    redirect_to '/'

    # binding.pry
    # respond_to do |format|
    #   format.html { '/' }
    #   format.json { render json: @list } #this is the response for the AJAX call.
    # end

    # respond_to do |format|
    #   if @list.update_attributes(list_params)
    #     format.html { redirect_to '/'}
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @image.errors, status: :unprocessable_entity }
    #   end
    # end

  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to '/'
  end

  private

  def list_params
    return params[:list].permit(:title, :position_y, :position_x)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>

  <p>
    <%= f.text_area :description, :size=>"50x10" %>
    <%= f.hidden_field :list_id, { :value => @list.id }  %>
  </p>

  <p>

    <%= f.submit value: "Submit"%>
  </p>

<% end %>

<%= button_to "Cancel", :back, method: :get %>

app/views/items/edit.html.erb
<nav></nav>

<main>
  <div class = "new_item_form">

    <h2>Edit List Item:</h2>

    <%= render 'form' %>

  </div>
</main>

app/views/items/index.html.erb
<h1>Items Index Page</h1>

app/views/items/new.html.erb
<nav></nav>

<main>
  <div class = "new_item_form">

    <h2>Create New List Item:</h2>

    <%= render 'form' %>
    
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,700|Karla:400,700|Bree+Serif' rel='stylesheet' type='text/css'>  <%= csrf_meta_tags %>
    <script src = "https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/ui-lightness/jquery-ui.css">

  </head>
  <body>

    <header>
      <h1><%= link_to "Listy", '/',  class: "row"%></h1>
    </header>

    <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <p>
    <%= f.text_field :title, :size=>"52", :placeholder=>"List Title" %>
  </p>

  <p>
    <%= f.submit value: "Submit"%>
  </p>

<% end %>

<%= button_to "Cancel", :back, method: :get %>

app/views/lists/edit.html.erb
<div class = "new_list_form">

  <h2>Edit List:</h2>

  <%= render 'form' %>

</div>

app/views/lists/index.html.erb
<nav>
  <div class="options row">
    <%= button_to 'Add New List', new_list_path, method: :get, class: "option-button" %>
  </div>
</nav>

<main>
  <% @lists.each do |list| %>
    <% if list.position_x.nil? or list.position_y.nil? %>
      <%= link_to(list.title.upcase, list_path(list), method: :get, class: "list", id:"#{list.id}" ) %>
    <% else %>
      <%= link_to(list.title.upcase, list_path(list), method: :get, class: "list", id:"#{list.id}", style:"position:absolute; top:#{list.position_y}px;left:#{list.position_x}px; " ) %>
    <% end %>


  <% end %>
</main>

app/views/lists/new.html.erb
<nav></nav>

<main>
  <div class = "new_list_form">

    <h2>Create New List:</h2>

    <%= render 'form' %>

  </div>
</main>

app/views/lists/show.html.erb
<nav>
  <div class="options">
    <%= button_to 'Add New List Item', new_list_item_path(@list), method: :get, class: "option-button" %>
    <%= button_to 'Edit List Title', edit_list_path(@list), method: :get, class: "option-button" %>
    <%= button_to 'Delete List', list_path(@list), method: :delete, class: "option-button" %>
  </div>
</nav>

<main>
  <div class ="list_items">

    <div class = "title row">
      <%= @list.title %>
    </div>

    <div class = "items row">
        <% @list.items.each do |item| %>
          <div class="row item">

            <div class="list_item">
              <span class="wrapper">
              <%= button_to "x", list_item_path(@list, item), method: :delete, class:"delete" %>
              <p class="hoverCaption">DELETE ME</p>
              </span>

              <span class="checkWrapper">

                <span class="markComplete" id="<%=item.id%>">&#10003;
                  <p class="hoverCaption">COMPLETE ME</p>
                </span>

                <span class="editItem">
                  <p class="hoverCaption">EDIT ME</p>
                  <% if item.completed %>
                    <%= link_to item.description, edit_list_item_path(@list, item), class:"itemText itemComplete"%>
                  <% else %>
                    <%= link_to item.description, edit_list_item_path(@list, item), class:"itemText"%>
                  <% end %>
                </span>

              </span>
            </div>

          </div>
        <% end %>
    </div>

  </div>
</main>